import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeProvider from './provider'
import Header from '@/components/Header'
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > 
           <div className='min-h-screen min-w-screen flex flex-col items-center pt-0 md:pt-8 lg:pt-14'>
              <Header />
              {children}
           </div>
          </ThemeProvider>
      </body>
    </html>
  )
}
